### ISSUE TITLE
Redesign the footer properly with only relevant links.

### ISSUE THREAD

**Issue by nishihere19** [Letusmeet/letsmeet#9]

**Comment by slowloris-x** [comment]
I checked it and it is responsive already, which links you meant as there is only singin and singup links

**Comment by nishihere19** [comment]
Oh, I meant that the footer should be redesigned properly with only the relevant links.

**Comment by nishihere19** [comment]
For now, it is just a template.

**Comment by slowloris-x** [comment]
Yeah, ok let me do something for it and pull it asap

**Comment by nishihere19** [comment]
Great! Go ahead.
